export enum SetType {
    Alchemy = 'alchemy',
    Archenemy = 'archenemy',
    Arsenal = 'arsenal',
    Box = 'box',
    Commander = 'commander',
    Core = 'core',
    DraftInnovation = 'draft_innovation',
    DuelDeck = 'duel_deck',
    Expansion = 'expansion',
    FromTheVault = 'from_the_vault',
    Funny = 'funny',
    Masterpiece = 'masterpiece',
    Masters = 'masters',
    Memorabilia = 'memorabilia',
    Minigame = 'minigame',
    Planechase = 'planechase',
    Premium_deck = 'premium_deck',
    Promo = 'promo',
    Spellbook = 'spellbook',
    Starter = 'starter',
    Token = 'token',
    TreasureChest = 'treasure_chest',
    Vanguard = 'vanguard',
}
