version: '3.8'

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/web:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  etl:
    image: ghcr.io/${GITHUB_REPOSITORY}/etl:${IMAGE_TAG:-latest}
    restart: "no"  # Run once, don't restart
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=info
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - app-network
    # Don't expose ports in production

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_prod_data:/data
    networks:
      - app-network

  # Reverse proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_prod_data:
  redis_prod_data:

networks:
  app-network:
    driver: bridge