services:
  # Web Application
  web:
    image: ghcr.io/matthewdtowles/i-want-my-mtg/web:latest
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Scry - ETL Application
  etl:
    image: ghcr.io/matthewdtowles/i-want-my-mtg/etl:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SCRY_LOG=${SCRY_LOG}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["etl"]
    restart: "no"

  # PostgreSQL Database (shared by web and etl)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_prod_data:

# No networks - handled by Docker Compose by default