#!/bin/bash
# Regenerate src/http/cloudfront-origin-ranges.ts from AWS's published address list.
# Only CloudFront's origin-facing ranges are kept: those are the addresses CloudFront
# connects to our server from, and the only ones the app trusts to report a visitor's
# address (#622). Run it now and then; a stale list is safe, just less precise.
# Usage: ./scripts/update-cloudfront-ranges.sh

set -euo pipefail

OUT="$(dirname "$0")/../src/http/cloudfront-origin-ranges.ts"

curl -fsS https://ip-ranges.amazonaws.com/ip-ranges.json | node -e '
let raw = "";
process.stdin.on("data", (c) => (raw += c)).on("end", () => {
    const d = JSON.parse(raw);
    const pick = (list, key) =>
        list.filter((p) => p.service === "CLOUDFRONT_ORIGIN_FACING").map((p) => p[key]).sort();
    const ranges = [...pick(d.prefixes, "ip_prefix"), ...pick(d.ipv6_prefixes, "ipv6_prefix")];
    if (ranges.length === 0) throw new Error("No CLOUDFRONT_ORIGIN_FACING ranges found");
    const lines = ranges.map((r) => `    '"'"'${r}'"'"',`).join("\n");
    process.stdout.write(
        "// Generated by scripts/update-cloudfront-ranges.sh from ip-ranges.json " +
            `(createDate ${d.createDate}). Do not edit by hand.\n` +
            "export const CLOUDFRONT_ORIGIN_FACING_RANGES: readonly string[] = [\n" +
            lines +
            "\n];\n"
    );
});
' > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "Wrote $(grep -c "^    '" "$OUT") ranges to $OUT"
