name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run App Unit Tests
        run: |
          cp .env.example .env
          docker compose run --rm web npm test

      - name: Cleanup
        run: docker compose down -v

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Install OpenSSL for musl
        run: sudo apt-get update && sudo apt-get install -y musl-tools musl-dev libssl-dev
      - name: Build ETL Binary
        run: |
          cd scry
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/scry

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Web App
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web:${{ github.sha }}

      # Remove the ETL Docker build step since we're using binary

      - name: Upload ETL Binary
        uses: actions/upload-artifact@v4
        with:
          name: scry-binary
          path: scry/target/x86_64-unknown-linux-musl/release/scry

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ETL Binary
        uses: actions/download-artifact@v4
        with:
          name: scry-binary
          path: ./

      - name: Deploy to Production LightSail Instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_PK }}
          LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIGHTSAIL_GITHUB_TOKEN: ${{ secrets.LIGHTSAIL_GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SCRY_LOG: ${{ secrets.SCRY_LOG }}
        run: |
          # Setup SSH key
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Create .env file
          cat > .env <<EOF
          APP_NAME=i-want-my-mtg
          DATABASE_URL=$DATABASE_URL
          JWT_SECRET=$JWT_SECRET
          NODE_ENV=$NODE_ENV
          POSTGRES_DB=$POSTGRES_DB
          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          SCRY_LOG=$SCRY_LOG
          LIGHTSAIL_GITHUB_TOKEN=$LIGHTSAIL_GITHUB_TOKEN
          EOF

          # Make binary executable
          chmod +x scry

          # Copy files to server
          scp -o StrictHostKeyChecking=no -i private_key docker-compose.prod.yml ubuntu@$LIGHTSAIL_IP:~/
          scp -o StrictHostKeyChecking=no -i private_key .env ubuntu@$LIGHTSAIL_IP:~/
          scp -o StrictHostKeyChecking=no -i private_key scry ubuntu@$LIGHTSAIL_IP:~/
          scp -o StrictHostKeyChecking=no -i private_key -r docker/ ubuntu@$LIGHTSAIL_IP:~/

          # Deploy on server
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$LIGHTSAIL_IP <<'EOF'
            # Login to GHCR
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Rename prod compose file to standard name
            mv docker-compose.prod.yml docker-compose.yml

            # Stop existing containers
            docker compose down || true

            # Pull latest images
            docker compose pull

            # Start PostgreSQL first to ensure it's ready
            docker compose up -d postgres
            
            # Wait for PostgreSQL to be healthy
            timeout 60 bash -c 'until docker compose exec postgres pg_isready -U $POSTGRES_USER; do sleep 2; done'

            # Error handling for DB startup
            if [ $? -eq 0 ]; then
              echo "PostgreSQL is ready!"
            else
              echo "PostgreSQL failed to start!"
              docker compose logs postgres
              exit 1
            fi

            echo "Starting web service..."
            docker compose up -d web

            # Make ETL binary executable
            chmod +x ~/scry

            # Deployment verification
            sleep 10
            echo "Checking service status..."
            docker compose ps
            docker compose logs web --tail=10

            echo "Testing web service connectivity..."
            timeout 30 bash -c 'until curl -f http://localhost:3000/health || curl -f http://localhost:3000; do echo "Waiting for web service..."; sleep 2; done' || {
              echo "Web service failed to respond!"
              docker compose logs web
              exit 1
            }

            echo "Deployment successful!"
            echo "ETL binary available at: ~/scry"
            
            # Test ETL binary
            echo "Testing ETL binary..."
            ./scry --version || echo "ETL binary test failed"

            docker image prune -f
          EOF

          # Cleanup local SSH key
          rm private_key